### ISSUE TITLE
Source maps are referenced but not included in the NPM package 

### ISSUE THREAD

**Issue by fungiboletus** [Borewit/token-types#205]
Hi,

Like https://github.com/Borewit/strtok3/issues/365 and https://github.com/Borewit/peek-readable/issues/229, the package published on NPM contains`//# sourceMappingURL=index.js.map` at the end of the `index.js` file but `index.js.map` is missing from the package.

It's not a real issue but VSCode started to complain about it. See https://github.com/microsoft/vscode/issues/102042

Thanks 🙂

**Comment by Borewit** [comment]
Thanks for your feedback @fungiboletus, I will remove the mapping files from the distribution.
