### ISSUE TITLE
use dataview instead?

### ISSUE THREAD

**Issue by jimmywarting** [Borewit/token-types#245]
DataView is fast in v8 now
could you perhaps switch to operate on Uint8Array + DataView so it would make it less dependent on NodeJS Buffer module so the browser bundle wouldn't have to be as big?

**Comment by Borewit** [comment]
Good to see you around @jimmywarting!

I was not aware of the [DataView](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) option. Sound like a good idea to me, I this is worth trying.

**Comment by jimmywarting** [comment]
I guess a few ppl stuck with Buffer since DataView was slow up until 2018
https://v8.dev/blog/dataview

Think mixing buffer with Uint8arrays cusses some confusion sometimes. 
if you read https://jakearchibald.com/2021/function-callback-risks/ then you might know what i mean
You shouldn't be using Buffer if they where intended to only behave as uint8arrays. one might decide to replace buffer with just plain uint8array to reduce the browser bundle (like you are doing now) and some other who depends on your lib expected a Buffer in return... its just better to restrict this rule and say "In node this might can be a Buffer coming from some arbitrary place but in the browser they are Uint8Array so treat it as such!"

I wrote a [style guide](https://github.com/cross-js/cross-js/blob/master/README.md) on how to best write cross javascript application a while back
Might be of interest to you

**Comment by Borewit** [comment]
Can you please review PR #246 @jimmywarting ?
