### ISSUE TITLE
Thoughts about using # instead of private?

### ISSUE THREAD

**Issue by jimmywarting** [Borewit/token-types#314]
`#` is the defacto way off writing private methods nowdays.
anything that isn't `#` is a public method.

https://github.com/Borewit/token-types/blob/b74898998e553333e0fbd4b8c1ddb8d059e465ed/lib/index.ts#L424

I expect public/private to fade away eventually... some linters recommend it instead cuz it's the "right way" to write it

it makes it also more clear when you look at a piece of code and you can instantly tell if a method is a private method just by looking at `this.#`
I was debugging a other code to look what it was doing and saw: "ah this method seems interesting, i wonder if i can use it directly instead", but turned out that method was private when i tried to use it. Would have instantly know if it had `this.#foo()` instead...

**Comment by Borewit** [comment]
It looks I am getting old @jimmywarting, if you say that the new way of writing private member functions, it's fine by me.
