### ISSUE TITLE
Signed 8-Bit Integer Return Offset

### ISSUE THREAD

**Issue by jodhus** [Borewit/token-types#410]
Forgive me if I'm reporting a false alarm, but I'm still wrapping my head around tokenizers. I was looking at `lib/index.ts` and saw that the 8-bit signed integer is returning `offset + 2`. Shouldn't this be `offset + 1`, or am I misunderstanding what's happening here?

Lines 130-145:
```typescript
/**
 * 8-bit signed integer
 */
export const INT8: IToken<number> = {

  len: 1,

  get(array: Uint8Array, offset: number): number {
    return dv(array).getInt8(offset);
  },

  put(array: Uint8Array, offset: number, value: number): number {
    dv(array).setInt8(offset, value);
    return offset + 2;
  }
};
```

**Comment by Borewit** [comment]
Yeah painful, good catch. I am not using the encoding (`put`) methods myself, which is probably the reason I never noticed it.
