### ISSUE TITLE
Issue with determining epub file type getting added empty line

### ISSUE THREAD

**Issue by rahul-singh-sf** [Borewit/token-types#455]
[lib/index.ts](https://github.com/Borewit/token-types/blob/master/lib/index.ts)
`class StringType {
    constructor(len, encoding) {
        this.len = len;
        this.encoding = encoding;
    }
    get(uint8Array, offset) {
        return Buffer.from(uint8Array).toString(this.encoding, offset, offset + this.len);
    }
}`

Expected value: 'application/epub+zip'
Actual value: 'application/epub+zip
'
Some of the links for the epub files are here:-
[https://soundplay-reports.s3.amazonaws.com/1.epub](https://soundplay-reports.s3.amazonaws.com/1.epub)
[https://soundplay-reports.s3.amazonaws.com/2.epub](https://soundplay-reports.s3.amazonaws.com/2.epub)

Issue is raised in npm file-type
https://github.com/sindresorhus/file-type/issues/537

Resolution
The extra space should be truncated by the library.

**Comment by rahul-singh-sf** [comment]
@Borewit We can trim string to remove extra space.
`export class StringType implements IGetToken<string, Buffer> {

  public constructor(public len: number, public encoding: BufferEncoding) {
  }

  public get(uint8Array: Uint8Array, offset: number): string {
    return Buffer.from(uint8Array).toString(this.encoding, offset, offset + this.len).trim();
  }
}`

**Comment by Borewit** [comment]
If you want to trim the resulting string then trim it. There is no need to change token-types.
